# https://gohugo.io/getting-started/configuration/
baseURL = "https://zoshigayan.net"
defaultContentLanguage = "ja"
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "ja-JP"
paginate = 30
title = "雑司ヶ谷インターネット"
copyright = "2020 (C) zoshigayan"
googleAnalytics = "UA-171113618-1"
[params]
description = "インターネットは、あるんだよ"
[permalinks]
posts = "/:filename"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "api"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
      unsafe = true
