# https://gohugo.io/getting-started/configuration/
baseURL = "https://zoshigayan.net"
defaultContentLanguage = "ja"
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "ja-JP"
paginate = 30
title = "雑司ヶ谷ブログ"
copyright = "2020 (C) zoshigayan"
googleAnalytics = "UA-171113618-1"
summaryLength = 300
theme="toshima"

[menu]
[[menu.header]]
name="トップ"
url="/"
weight=1
[[menu.header]]
name="知見"
url="/knowledges"
weight=2
[[menu.header]]
name="雑記"
url="/random"
weight=3
[[menu.header]]
name="引用"
url="/quotes"
weight=4
[[menu.header]]
name="RSS"
url="/index.xml"
weight=5


[params]
description = "ギリギリ生きているWeb系プログラマのブログです"
  [params.profile]
    name="zoshigayan"
    icon="/prof_dark.png"
    bio="Web Application Developer / Project Manager"
    [[params.profile.links]]
      name="email"
      url="mailto:hello@zoshigayan.net"
    [[params.profile.links]]
      name="twitter"
      url="https://twitter.com/zoshigayan"
    [[params.profile.links]]
      name="github"
      url="https://github.com/zoshigayan"
    [[params.profile.links]]
      name="steam"
      url="https://steamcommunity.com/id/zoshigayan"


[permalinks]
knowledges = "/knowledges/:slug"
random = "/random/:slug"
quotes = "/quotes/:slug"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "swapoff"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
      unsafe = true
